# Generated by Django 5.2.1 on 2025-05-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_url', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.artist')),
            ],
            options={
                'db_table': 'hit',
            },
        ),
    ]
