# Generated by Django 5.2.1 on 2025-05-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
